/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Adrian
 */
public class Juego_Coins extends JuegoGenerico {

    private int[][] tablero = new int[25][25];
    /*
    private final int GOOD_COINS = 313;
    private final int BAD_COINS = 312;
    private int bad_count, good_count;
    */
    public static final int BUTTON_SIZE = 32;
    private Jugador Jugador;
    private JButton buttonArray[][] = new JButton[25][25];
    public int tiempoRestante;
    public int puntaje = 0;
    public Timer conteo;
    
    
    /**
     * Creates new form Juego_Coins
     */
    public Juego_Coins(Jugador Jugador) {
        this.Jugador = Jugador;
        // hace el tiempo restante de forma aleatoria
        int randTime = 1 + (int)(Math.random() * ((3 - 1) + 1));
        tiempoRestante = switch (randTime) {
            case 1 -> 30;
            case 2 -> 45;
            case 3 -> 60;
            default -> 45;
        };
        
        initComponents();
        generateBoard();
        conteo = new Timer(1000, listenerTimer);
        conteo.setInitialDelay(1);
        conteo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scoreField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        changesArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setPreferredSize(new java.awt.Dimension(800, 800));
        panelPrincipal.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PUNTOS");

        scoreField.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        scoreField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        scoreField.setText("0");
        scoreField.setToolTipText("");

        changesArea.setColumns(20);
        changesArea.setRows(5);
        jScrollPane1.setViewportView(changesArea);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIEMPO");

        timeField.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        timeField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        timeField.setText("0");
        timeField.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void generateBoard() {
        int valorAleatorio;
        for (int i = 0; i < 25; i++) {
            for (int j = 0; j < 25; j++) {
                // valor de la casilla
                valorAleatorio = -10 + (int)(Math.random() * ((10 - -10) + 1));
                tablero[i][j] = valorAleatorio;
                // inicializar el boton
                buttonArray[i][j] = new JButton();
                panelPrincipal.add(buttonArray[i][j]);
                buttonArray[i][j].setBounds(j * BUTTON_SIZE, i * BUTTON_SIZE, BUTTON_SIZE, BUTTON_SIZE);
                buttonArray[i][j].setBackground(new Color(230 + i, 220 + j, 25 + (j - i)));
                buttonArray[i][j].addActionListener(listenerBoton);
                
                //System.out.print(tablero[i][j] + " ");
            }
            //System.out.println("");
        }
    }
    
    public void updateScore() {
        scoreField.setText(Integer.toString(puntaje));
    }
    
    public void addHistory(int change) {
        if (change >= 0) {
            changesArea.append("+" + Integer.toString(change) + "\n");
        }
        else {
            changesArea.append(Integer.toString(change) + "\n");
        }
    }
    
    ActionListener listenerBoton = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            int x, y;
            if (e.getSource() instanceof JButton) {  
                x = ((JButton) e.getSource()).getX() / BUTTON_SIZE;
                y = ((JButton) e.getSource()).getY() / BUTTON_SIZE;
                
                puntaje += tablero[y][x];
                updateScore();
                addHistory(tablero[y][x]);
                ((JButton) e.getSource()).setEnabled(false);
            }
        }
    };
    
    ActionListener listenerTimer = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            timeField.setText(tiempoRestante-- + "");
            if (tiempoRestante <= 0) {
                if (puntaje < 0) {
                    JOptionPane.showMessageDialog(null, "Perdió el juego con " + puntaje + " puntos", "Perdedor", 0);
                    ((Timer) e.getSource()).stop();
                    Jugador.setEsGanador(true); // esPerdedor
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Ganó el jeugo con " + puntaje + " puntos", "Ganador", 1);
                    ((Timer) e.getSource()).stop();
                    dispose();
                }
            }
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea changesArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField scoreField;
    private javax.swing.JTextField timeField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEnemigo(String nombreEnemigo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
