/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author tcoto
 */
public class Juego_Path extends javax.swing.JFrame {
    private JButton buttonArray[][] = new JButton[6][3];
    private boolean camino[][] = new boolean[6][3];
    private int count = 0;
    
    /**
     * Creates new form Memory_path
     */
    public Juego_Path() {
        initComponents();
        initBoard();
        for (int i = 0; i < 6; i++){
            System.out.println(camino[i][0] + " " + camino[i][1] + " " + camino[i][2]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     */
    public void initBoard(){
        int Button_size = 50;
        for (int i = 0; i < 6; i++){
            for (int j = 0; j < 3; j++){
                //System.out.println("HLA");
                buttonArray[i][j] = new JButton((6-i)+"");
                camino[i][j] = false;
                jPanel1.add(buttonArray[i][j]);
                buttonArray[i][j].setBounds(j * Button_size, i * Button_size, Button_size, Button_size);  
                buttonArray[i][j].addActionListener(listener);
            }
            int  true_camino = new Random().nextInt(2);
            camino[i][true_camino] = true;
        }
    }
    
    public boolean point_and_win(int y, int x){
        
        if (count <= 5 && camino[y][x] == true){
            
            if (count == 5){
                JOptionPane.showMessageDialog(this,"Gano", "Ganador", JOptionPane.INFORMATION_MESSAGE);
                super.dispose();
            }
            count++; 
            return true;
        }
        else{
            count = 0;
        }
        return false;
    }
    ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            int x, y;
            if (e.getSource() instanceof JButton) {  
                x = ((JButton) e.getSource()).getX() / 50;
                y = ((JButton) e.getSource()).getY() / 50;
                point_and_win(y, x);
            }
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
