    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;

/**
 *
 * @author diemo
 */
public class Tablero extends javax.swing.JFrame {
    public static final int BUTTON_SIZE = 120;
    public static final int BOARD_SIZE = 26;
    private JButton buttonArray[] = new JButton[BOARD_SIZE];
    
    
    private int turno = 1;
    private Color colorArray[] = {Color.red, Color.yellow, Color.BLUE, Color.GREEN, Color.pink, Color.white}; 
    ArrayList<Jugador> playerArray = new ArrayList<Jugador>();

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        initPlayers();
        initBoard();
    }
    
    
    public void initPlayers(){
        
        int playersQty = (new Random()).nextInt(5)+2;
        
        for (int i = 0; i < playersQty; i++) {
            JButton newButton = new JButton("" + (i+1));
            newButton.setBackground(colorArray[i]);
            jPanel1.add(newButton);
            newButton.setBounds(0, i*20, 40, 20);
            playerArray.add(new Jugador("Jugador " + (i+1), i, newButton));            
        }
        
    }
    
    public void initBoard(){
        for (int i = 0; i < buttonArray.length; i++) {
            buttonArray[i] = new JButton((i+1)+"");
            jPanel1.add(buttonArray[i]);
            
            if (i <= 7)
                buttonArray[i].setBounds(i*BUTTON_SIZE, 0, BUTTON_SIZE, BUTTON_SIZE);
            else if (i >=8 && i <= 12)
                buttonArray[i].setBounds(840, (i-4) * BUTTON_SIZE, BUTTON_SIZE, BUTTON_SIZE);
            else if (i >=13 && i <= 20)
                buttonArray[i].setBounds(840-(i-13)* BUTTON_SIZE, 720 , BUTTON_SIZE, BUTTON_SIZE);
            else
                buttonArray[i].setBounds(0, 600-(i-21)* BUTTON_SIZE, BUTTON_SIZE, BUTTON_SIZE);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDados = new javax.swing.JButton();
        txfDados = new javax.swing.JTextField();
        lblTurno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );

        btnDados.setText("Lanzar dados");
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });

        txfDados.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblTurno.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTurno.setText("Turno 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDados)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txfDados, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfDados, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        int valorDados = this.lanzarDados();
        this.txfDados.setText(valorDados + "");
        moverFicha(valorDados);
        pintarTurno();
    }//GEN-LAST:event_btnDadosActionPerformed

    
    private void moverFicha(int avance){
        Jugador jugadorActual = playerArray.get(turno-1);
        jugadorActual.avanzarCasillaActual(avance);
        JButton botonFicha = playerArray.get(turno-1).getRefButton();
        Point pto = botonFicha.getLocation();
        
        //ubicacion de la casilla donde cayo. x,y
        Point ptoCasilla = buttonArray[jugadorActual.getCasillaActual()-1].getLocation();

        botonFicha.setLocation(ptoCasilla.x, ptoCasilla.y + jugadorActual.getIndex() * 20);
    }
    
    private void setNextTurno(){
        turno++;
        if(turno > playerArray.size())
            turno = 1;
    }
    
    private int lanzarDados(){
        int dado1 = (new Random()).nextInt(6) + 1;
        int dado2 = (new Random()).nextInt(6) + 1;
        
        return dado1+dado2;
    }
    
    private void pintarTurno(){
        setNextTurno();
        lblTurno.setText("Turno " + this.turno);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextField txfDados;
    // End of variables declaration//GEN-END:variables
}
